'use strict';
const $=id=>document.getElementById(id),DATA=window.OUTBOUND_DATA,NS='http://www.w3.org/2000/svg';
const categories={'bottle-cap':{name:'Bottle caps',single:'Bottle cap pickup',icon:'◉',color:'#bd964a'},poi:{name:'Structures & landmarks',single:'Point of interest',icon:'⌂',color:'#6b8061'},'blueprint-terminal':{name:'Signal towers',single:'Signal tower',icon:'⌁',color:'#51867d'},campfire:{name:'Campfires',single:'Campfire',icon:'♨',color:'#ad8140'},'cap-snaps':{name:"Cap 'n Snaps",single:"Cap 'n Snaps",icon:'▣',color:'#b28065'},fishing:{name:'Fishing spots',single:'Fishing spot',icon:'≈',color:'#4c83ac'},gnome:{name:'Gnomes',single:'Gnome',icon:'▲',color:'#ba624c'},cairn:{name:'Cairns',single:'Cairn',icon:'◆',color:'#7e7b64'},painting:{name:'Paintings',single:'Painting',icon:'▧',color:'#aa6992'},personal:{name:'My pins',single:'Personal pin',icon:'⚑',color:'#856d9e'}};
const KEY='outbound-atlas-v1';let saved={found:[],notes:{},pins:[]};
let storageProblem=false;try{const raw=JSON.parse(localStorage.getItem(KEY));if(raw){try{saved=AtlasState.validate(raw,DATA.regions);}catch{saved=AtlasState.recover(raw,DATA.regions);storageProblem=true;try{localStorage.setItem(KEY+'-recovery',JSON.stringify(raw));}catch{}}}}catch{storageProblem=true;}
let found=new Set(saved.found),notes=saved.notes,pins=saved.pins,region=DATA.regions[0],enabled=new Set(Object.keys(categories)),selected=null,adding=false,pending=null,view={x:0,y:0,w:2048,h:2048};
const map=$('map');let toastTimer;
const mobileLayout=matchMedia('(max-width:760px)');function syncSidebar(){$('sidebar').inert=mobileLayout.matches&&!document.body.classList.contains('menu-open');}mobileLayout.addEventListener('change',syncSidebar);new MutationObserver(syncSidebar).observe(document.body,{attributes:true,attributeFilter:['class']});syncSidebar();
function notify(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3500);}
function save(){try{localStorage.setItem(KEY,JSON.stringify({found:[...found],notes,pins}));return true;}catch{notify('Storage unavailable: export your progress to keep it.');return false;}}
function allPoints(){return [...DATA.points,...pins];}
function name(p){if(p.category==='gnome')return p.name.replace(/^gnome-(\d+) - /i,'$1 · ');return p.displayName||p.name;}
function visible(){const q=$('search').value.trim().toLocaleLowerCase('en');return allPoints().filter(p=>p.scene===region.id&&enabled.has(p.category)&&(!$('hideFound').checked||!found.has(p.id))&&(!q||(name(p)+' '+categories[p.category].name).toLocaleLowerCase('en').includes(q)));}
function xy(p){const b=region.bounds;return{x:(p.x-b.minX)/b.sizeX*2048,y:(1-(p.z-b.minZ)/b.sizeZ)*2048};}
function outside(p){const pos=xy(p);return pos.x<0||pos.x>2048||pos.y<0||pos.y>2048;}
function symbol(p){const el=document.createElement('span');el.className='symbol';el.style.background=categories[p.category].color;el.textContent=categories[p.category].icon;return el;}
function updateView(){map.setAttribute('viewBox',`${view.x} ${view.y} ${view.w} ${view.h}`);const s=view.w/map.clientWidth;document.querySelectorAll('.marker').forEach(el=>{const p=allPoints().find(x=>x.id===el.dataset.id),pos=xy(p);el.setAttribute('transform',`translate(${pos.x} ${pos.y}) scale(${s})`);});}
function fit(){const ratio=map.clientWidth/Math.max(1,map.clientHeight);view=ratio>=1?{x:-(2048*ratio-2048)/2,y:0,w:2048*ratio,h:2048}:{x:0,y:-(2048/ratio-2048)/2,w:2048,h:2048/ratio};updateView();}
function render(){
 const focusedCategory=document.activeElement?.dataset?.category;
 const regional=allPoints().filter(p=>p.scene===region.id),done=regional.filter(p=>found.has(p.id)).length;
 $('progressText').textContent=`${done} / ${regional.length} found`;$('percent').textContent=Math.round(done/Math.max(1,regional.length)*100)+'%';$('progress').value=done/Math.max(1,regional.length)*100;
 $('filters').replaceChildren();Object.entries(categories).forEach(([key,c])=>{const label=document.createElement('label');label.className='filter';label.append(symbol({category:key}));const text=document.createElement('span');text.textContent=c.name;label.append(text);const count=document.createElement('span');count.className='count';const items=regional.filter(p=>p.category===key);count.textContent=items.filter(p=>found.has(p.id)).length+' / '+items.length;label.append(count);const cb=document.createElement('input');cb.type='checkbox';cb.dataset.category=key;cb.checked=enabled.has(key);cb.setAttribute('aria-label',c.name);cb.onchange=()=>{cb.checked?enabled.add(key):enabled.delete(key);render();};label.append(cb);$('filters').append(label);});
 $('toggleAll').textContent=enabled.size?'Hide all':'Show all';
 const pts=visible();$('resultCount').textContent=pts.length;$('results').replaceChildren();$('markers').replaceChildren();
 for(const p of pts){const c=categories[p.category],isDone=found.has(p.id),btn=document.createElement('button');btn.className='result'+(isDone?' done':'')+(p.id===selected?' selected':'');btn.append(symbol(p));const title=document.createElement('span');title.textContent=name(p);const small=document.createElement('small');small.textContent=c.single+(outside(p)?' · Position unverified':'');title.append(small);btn.append(title);if(isDone){const check=document.createElement('span');check.textContent='✓';btn.append(check);}btn.onclick=e=>openPoint(p,true,e.detail===0);$('results').append(btn);
 const g=document.createElementNS(NS,'g');g.dataset.id=p.id;g.classList.add('marker');if(isDone)g.classList.add('done');if(selected===p.id)g.classList.add('selected');g.setAttribute('role','button');g.setAttribute('tabindex','0');g.setAttribute('aria-label',name(p)+(isDone?', found':''));const circle=document.createElementNS(NS,'circle');circle.setAttribute('r','12');circle.setAttribute('fill',c.color);circle.setAttribute('stroke','#f5eedb');circle.setAttribute('stroke-width','1.5');const text=document.createElementNS(NS,'text');text.setAttribute('text-anchor','middle');text.setAttribute('dy','.35em');text.setAttribute('font-size','14');text.textContent=isDone?'✓':c.icon;const tip=document.createElementNS(NS,'title');tip.textContent=name(p);g.append(circle,text,tip);g.onclick=e=>{e.stopPropagation();if(!dragMoved)openPoint(p,false);};g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openPoint(p,false,true);}};$('markers').append(g);
 }
 if(!pts.length){const empty=document.createElement('p');empty.className='empty';empty.textContent='No locations match your filters. Try another name or enable a category.';$('results').append(empty);}updateView();if(focusedCategory)document.querySelector(`[data-category="${focusedCategory}"]`)?.focus();
}
function openPoint(p,center,keyboard=false){selected=p.id;$('detail').hidden=false;$('pinForm').hidden=true;$('detailCategory').textContent=categories[p.category].single.toUpperCase();$('detailTitle').textContent=name(p);$('detailLocation').textContent=`${region.name} · X ${p.x.toFixed(1)} · Z ${p.z.toFixed(1)}`;$('positionWarning').hidden=!outside(p);if(outside(p))$('positionWarning').textContent='Position unverified: the extracted coordinates fall beyond the original map image. This marker has not been moved or clamped.';$('note').value=notes[p.id]||'';$('foundButton').textContent=found.has(p.id)?'✓ Found — undo':'Mark as found';$('deletePin').hidden=p.category!=='personal';if(center){const pos=xy(p),w=Math.min(view.w,900),h=w*map.clientHeight/map.clientWidth;view={x:pos.x-w/2,y:pos.y-h/2,w,h};}document.body.classList.remove('menu-open');$('mobileMenu').setAttribute('aria-expanded','false');syncSidebar();render();if(keyboard)$('closeDetail').focus();}
$('closeDetail').onclick=()=>{selected=null;$('detail').hidden=true;render();map.focus();};
$('foundButton').onclick=()=>{if(!selected)return;found.has(selected)?found.delete(selected):found.add(selected);save();openPoint(allPoints().find(p=>p.id===selected),false);};
$('note').oninput=()=>{if(selected){notes[selected]=$('note').value.slice(0,5000);save();}};
$('deletePin').onclick=()=>{pins=pins.filter(p=>p.id!==selected);found.delete(selected);delete notes[selected];selected=null;$('detail').hidden=true;save();render();};
for(const r of DATA.regions){const option=document.createElement('option');option.value=r.id;option.textContent=r.name;$('region').append(option);}
$('region').onchange=()=>{region=DATA.regions.find(r=>r.id===$('region').value);$('terrain').setAttribute('href','maps/'+region.image);$('mapTitle').textContent=region.name;selected=null;$('detail').hidden=true;$('pinForm').hidden=true;adding=false;$('addPin').setAttribute('aria-pressed','false');map.classList.remove('adding');pending=null;$('hint').textContent='Drag to explore · Scroll or + / − to zoom';$('search').value='';fit();render();};
$('search').oninput=render;$('hideFound').onchange=render;$('toggleAll').onclick=()=>{enabled=enabled.size?new Set():new Set(Object.keys(categories));render();};
function pointAt(e){const pt=map.createSVGPoint();pt.x=e.clientX;pt.y=e.clientY;return pt.matrixTransform(map.getScreenCTM().inverse());}
function zoom(factor,point={x:view.x+view.w/2,y:view.y+view.h/2}){const newW=Math.max(160,Math.min(6000,view.w*factor)),f=newW/view.w;view={x:point.x-(point.x-view.x)*f,y:point.y-(point.y-view.y)*f,w:newW,h:view.h*f};updateView();}
map.addEventListener('wheel',e=>{e.preventDefault();zoom(Math.exp(e.deltaY*.001),pointAt(e));},{passive:false});
$('zoomIn').onclick=()=>zoom(.75);$('zoomOut').onclick=()=>zoom(1/.75);$('fit').onclick=fit;
let pointers=new Map(),dragMoved=false,lastPinch=0,pressedMarker=null,suppressMapClick=false;
map.onpointerdown=e=>{if(e.button!==0)return;dragMoved=false;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});map.setPointerCapture(e.pointerId);pressedMarker=e.target.closest('.marker')?.dataset.id||null;suppressMapClick=!!pressedMarker;map.classList.add('dragging');if(pointers.size===2){const [a,b]=[...pointers.values()];lastPinch=Math.hypot(a.x-b.x,a.y-b.y);}};
map.onpointermove=e=>{const pos=pointAt(e),b=region.bounds;$('coords').textContent=`X ${Math.round(b.minX+pos.x/2048*b.sizeX)} · Z ${Math.round(b.minZ+(1-pos.y/2048)*b.sizeZ)} · N ↑`;if(!pointers.has(e.pointerId))return;const old=pointers.get(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const [a,b]=[...pointers.values()],distance=Math.hypot(a.x-b.x,a.y-b.y);if(lastPinch>0&&distance>0)zoom(lastPinch/distance,pointAt({clientX:(a.x+b.x)/2,clientY:(a.y+b.y)/2}));lastPinch=distance;dragMoved=true;}else{const dx=e.clientX-old.x,dy=e.clientY-old.y;if(Math.abs(dx)+Math.abs(dy)>1){dragMoved=true;view.x-=dx*view.w/map.clientWidth;view.y-=dy*view.h/map.clientHeight;updateView();}}};
function endPointer(e){if(e.type==='pointerup'&&!dragMoved&&pressedMarker){const point=allPoints().find(p=>p.id===pressedMarker);if(point)openPoint(point,false);}pressedMarker=null;pointers.delete(e.pointerId);if(!pointers.size)map.classList.remove('dragging');lastPinch=0;}
map.onpointerup=endPointer;map.onpointercancel=endPointer;map.onlostpointercapture=endPointer;window.addEventListener('blur',()=>{pointers.clear();pressedMarker=null;map.classList.remove('dragging');});
map.onclick=e=>{if(!adding||dragMoved||suppressMapClick||e.target.closest('.marker'))return;const pos=pointAt(e);if(pos.x<0||pos.y<0||pos.x>2048||pos.y>2048){notify('Choose a point inside the map.');return;}pending=pos;$('pinForm').hidden=false;$('detail').hidden=true;$('pinName').value='';$('pinName').focus();};
$('addPin').onclick=()=>{adding=!adding;map.classList.toggle('adding',adding);$('addPin').setAttribute('aria-pressed',String(adding));$('hint').textContent=adding?'Click the map to add a personal pin':'Drag to explore · Scroll or + / − to zoom';};
$('cancelPin').onclick=()=>{$('pinForm').hidden=true;pending=null;};
$('pinForm').onsubmit=e=>{e.preventDefault();const title=$('pinName').value.trim();if(!title||!pending)return;const b=region.bounds,p={id:'personal-'+crypto.randomUUID(),scene:region.id,region:region.name,category:'personal',name:title,x:b.minX+pending.x/2048*b.sizeX,y:0,z:b.minZ+(1-pending.y/2048)*b.sizeZ};pins.push(p);enabled.add('personal');save();pending=null;adding=false;map.classList.remove('adding');$('addPin').setAttribute('aria-pressed','false');$('hint').textContent='Drag to explore · Scroll or + / − to zoom';openPoint(p,false);};
map.onkeydown=e=>{if(e.target!==map)return;const delta=view.w*.1;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-','0'].includes(e.key))e.preventDefault();if(e.key==='ArrowLeft')view.x-=delta;if(e.key==='ArrowRight')view.x+=delta;if(e.key==='ArrowUp')view.y-=delta;if(e.key==='ArrowDown')view.y+=delta;if(e.key==='+'||e.key==='=')zoom(.75);if(e.key==='-')zoom(1/.75);if(e.key==='0')fit();updateView();};
$('mobileMenu').onclick=()=>{const open=document.body.classList.toggle('menu-open');$('mobileMenu').setAttribute('aria-expanded',String(open));};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,found:[...found],notes,pins},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='outbound-progress.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Progress exported.');};
$('import').onclick=()=>$('importFile').click();
$('importFile').onchange=async()=>{try{const file=$('importFile').files[0];if(!file)return;if(file.size>2000000)throw Error('File too large.');const d=JSON.parse(await file.text());if(d.version!==1||!Array.isArray(d.found)||!Array.isArray(d.pins)||!d.notes||typeof d.notes!=='object'||Array.isArray(d.notes))throw Error('Invalid format.');AtlasState.validate(d,DATA.regions);const merged=new Map(pins.map(p=>[p.id,p]));d.pins.forEach(p=>merged.set(p.id,p));pins=[...merged.values()];const ids=new Set(allPoints().map(p=>p.id));d.found.filter(id=>ids.has(id)).forEach(id=>found.add(id));for(const [id,n]of Object.entries(d.notes))if(ids.has(id))notes[id]=n;const stored=save();render();if(selected){const p=allPoints().find(p=>p.id===selected);if(p&&p.scene===region.id)openPoint(p,false);else{selected=null;$('detail').hidden=true;}}if(stored)notify('Progress imported and merged with your existing data.');}catch(e){notify('Could not import: '+e.message);}finally{$('importFile').value='';}};
let previousWidth=0,previousHeight=0;new ResizeObserver(()=>{const w=map.clientWidth,h=map.clientHeight;if(!w||!h)return;if(!previousWidth)fit();else{const cx=view.x+view.w/2,cy=view.y+view.h/2,scale=view.w/previousWidth;view={x:cx-w*scale/2,y:cy-h*scale/2,w:w*scale,h:h*scale};updateView();}previousWidth=w;previousHeight=h;}).observe(map);
document.addEventListener('keydown',e=>{if(e.key==='Escape'){selected=null;$('detail').hidden=true;$('pinForm').hidden=true;pending=null;adding=false;map.classList.remove('adding');$('addPin').setAttribute('aria-pressed','false');document.body.classList.remove('menu-open');$('mobileMenu').setAttribute('aria-expanded','false');$('hint').textContent='Drag to explore · Scroll or + / − to zoom';render();map.focus();}});
if(storageProblem)setTimeout(()=>notify('Some saved data could not be read. Valid entries were recovered where possible; export a backup before making changes.'),0);$('terrain').setAttribute('href','maps/'+region.image);$('mapTitle').textContent=region.name;render();fit();
